"""update models relationship

Revision ID: 26327abd8b73
Revises: 4a7d2335ff8c
Create Date: 2020-11-12 15:33:38.391426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26327abd8b73"
down_revision = "4a7d2335ff8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
