"""update models relationship

Revision ID: 419ae647a049
Revises: 26327abd8b73
Create Date: 2020-11-12 15:34:38.356197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "419ae647a049"
down_revision = "26327abd8b73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
