"""update models relationship

Revision ID: 4a7d2335ff8c
Revises: 62a3f92dd0cc
Create Date: 2020-11-12 15:32:59.464173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a7d2335ff8c"
down_revision = "62a3f92dd0cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
