"""update models relationship

Revision ID: 62a3f92dd0cc
Revises: c0e7e354b31c
Create Date: 2020-11-12 14:40:50.347735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a3f92dd0cc'
down_revision = 'c0e7e354b31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
