"""update models relationship

Revision ID: c0e7e354b31c
Revises: c49cef8274d1
Create Date: 2020-11-12 14:37:57.473341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0e7e354b31c'
down_revision = 'c49cef8274d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fly_from_id', sa.Integer(), nullable=True),
    sa.Column('fly_to_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.DateTime(), nullable=True),
    sa.Column('date_to', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fly_from_id'], ['iata.id'], ),
    sa.ForeignKeyConstraint(['fly_to_id'], ['iata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.drop_index('ix_plural_id', table_name='plural')
    op.drop_table('plural')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plural',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fly_from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fly_to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fly_from_id'], ['iata.id'], name='plural_fly_from_id_fkey'),
    sa.ForeignKeyConstraint(['fly_to_id'], ['iata.id'], name='plural_fly_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plural_pkey')
    )
    op.create_index('ix_plural_id', 'plural', ['id'], unique=False)
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
