"""update models relationship

Revision ID: dd9d051ca796
Revises: 419ae647a049
Create Date: 2020-11-12 15:35:11.071808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9d051ca796'
down_revision = '419ae647a049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
